# Function to display info
show_info() {
	echo "=================================="
	echo "     Dotfiles Installer - Info"
	echo "=================================="
	echo ""
	echo "This script helps you:"
	echo "  • Download configuration files (dotfiles) for:"
	echo "    - Hyprland"
	echo "    - Neovim (LazyVim setup)"
	echo "    - Kitty terminal"
	echo "    - Tmux"
	echo "    - Bash"
	echo "    - Oh-My-Posh (prompt theme)"
	echo ""
	echo "  • Download curated wallpapers:"
	echo "    - Minecraft (official)"
	echo "    - [JaKooLit] - (coming soon)"
	echo ""
	echo "  • Install configurations with one click"
	echo ""
	echo "Features:"
	echo "  • Clean separation between download and install phases"
	echo "  • Prevents overwriting existing directories"
	echo "  • Git-powered updates (via --depth 1 clone)"
	echo "  • Branch support (e.g., LazyVim)"
	echo ""
	echo "Maintained by: Miraj13123"
	echo "Repository: https://github.com/Miraj13123/dotfiles"
	echo ""
	echo "Note: This is a personal automation tool."
	echo "       Always review installer scripts before running."
	echo "=================================="
}